export const BANNER_KEYS = {
  GET_LIST: 'GET_BANNER_LIST',
  CHANGE_RANK_LIST: 'CHANGE_RANK_BANNER_LIST',
  SHOW: 'SHOW_BANNER',
  DELETE: 'DELETE_BANNER',
  GET: 'GET_BANNER',
  MODIFY: 'MODIFY_BANNER',
  CREATE: 'CREATE_BANNER',
} as const;
